name: gpu actions
on:
  workflow_dispatch:

jobs:
  nvidia-pod:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: gha-runner-actions-test
    container:
      image: nvidia/cuda:12.8.0-cudnn-runtime-rockylinux9
    steps:
    - run: echo "in nvidia container"
    - run: nvidia-smi
