name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: gha-runner-actions-test
    steps:
    - run: |
        echo "running in default container"
        ls -l /glade
        echo uid $UID
        id

  test-starting-container:
    runs-on: gha-runner-actions-test
    container:
      image: benjaminkirk/gh-ci-x86_64-almalinux9-oneapi-openmpi
    steps:
    - run: |
        echo "running in the custom container"
        ls -l /glade
        echo uid $UID
        id
