name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: cirrus-ml-github-runners
    steps:
    - run: echo "ðŸŽ‰ This job uses runner scale set runners!"

  test-starting-container:
    runs-on: cirrus-ml-github-runners
    container:
      image: rockylinux:9
    steps:
    - run: echo "running in the rocky container"
